apiVersion: v1
kind: PersistentVolume 
metadata:
  name: pv02
spec:
  capacity: 
    storage: 5Gi
  volumeMode: Filesystem 
  storageClassName: xxc
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Recycle 
  nfs:
    path: /pv02
    server: 192.168.97.60
