apiVersion: v1
kind: PersistentVolume 
metadata:
  name: pv03
spec:
  capacity: 
    storage: 5Gi
  volumeMode: Filesystem 
  storageClassName: xssf
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Recycle 
  nfs:
    path: /pv03
    server: 192.168.97.60
